#This file is for the purpose of monitoring on prometheus and Grafana 
#Does not matter what version is specified
version: '3' 

services: 
  zeus: 
    container_name: zeus-api
    build: 
    #Wherer yaml file can be found
      context: .
      #Where the dockerfile can be found 
      dockerfile: ./Dockerfile
    #Mapping of the port 
    ports: 
      - '3068:3068'
    #Containers auto restarting
    restart: 'on-failure'
#cadvisor gethers metrics from containers
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:lastest
    # contianer_name: cadvisor
    restart: always
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezeone:/etc/timezeone:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    devices: 
      - /dev/kmsg:dev/kmsg
    depends_on: 
      - zeus-api

