apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  k8s-app: metrics-server
resources:
  - metricsServer.apiservice.yaml
  - metricsServer.deployment.yaml
  - metricsServer.rbac.yaml
  - metricsServer.service.yaml
